#!/usr/bin/env bash
# Idempotent: installs WordPress + WooCommerce, configures the store, creates REST API keys and seeds demo data.
# Safe to run again; it only does what is missing. Run from this folder:  ./setup.sh
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
export MSYS_NO_PATHCONV=1   # Git Bash on Windows must not rewrite /seed and /var/www paths

if [ ! -f .env ]; then
  echo "No .env found. Copy .env.example to .env first (cp .env.example .env) and review it." >&2
  exit 1
fi
set -a; . ./.env; set +a

DC="docker compose --env-file .env"
wp() { $DC run --rm -T wpcli wp "$@"; }

log() { printf '\n==> %s\n' "$*"; }

log "Starting database and WordPress"
$DC up -d db wordpress

log "Waiting for WordPress files"
for i in $(seq 1 60); do
  if $DC exec -T wordpress test -f /var/www/html/wp-load.php; then break; fi
  sleep 2
  [ "$i" = 60 ] && { echo "WordPress files never appeared; check: $DC logs wordpress" >&2; exit 1; }
done
# The wordpress image creates wp-config.php on first start; give it a moment.
for i in $(seq 1 30); do
  if wp config path >/dev/null 2>&1; then break; fi
  sleep 2
done

if ! wp core is-installed >/dev/null 2>&1; then
  log "Installing WordPress at ${WP_SITE_URL}"
  wp core install --url="${WP_SITE_URL}" --title="${WP_SITE_TITLE}" --admin_user="${WP_ADMIN_USER}" \
    --admin_password="${WP_ADMIN_PASSWORD}" --admin_email="${WP_ADMIN_EMAIL}" --skip-email
else
  log "WordPress already installed"
  wp option update home "${WP_SITE_URL}" >/dev/null
  wp option update siteurl "${WP_SITE_URL}" >/dev/null
fi

log "Pretty permalinks (required by the REST API)"
wp rewrite structure '/%postname%/' --hard
wp rewrite flush --hard

log "Installing and activating WooCommerce"
wp plugin is-installed woocommerce || wp plugin install woocommerce --version="${WC_VERSION}" --activate
wp plugin is-active woocommerce || wp plugin activate woocommerce
# Create WooCommerce's tables / default pages if its own installer has not run yet.
wp eval 'if (function_exists("WC")) { WC_Install::install(); }' >/dev/null

log "Store basics"
wp option update woocommerce_currency "${WC_CURRENCY}"
wp option update woocommerce_default_country "${WC_COUNTRY}"
wp option update woocommerce_prices_include_tax "${WC_PRICES_INCLUDE_TAX}"
wp option update woocommerce_calc_taxes "no"
wp option update woocommerce_manage_stock "yes"
# A new store starts in "Coming soon" mode: visitors (and the product-page video) are hidden until it is launched.
wp option update woocommerce_coming_soon "no"
wp option update woocommerce_onboarding_profile '{"skipped":true}' --format=json >/dev/null 2>&1 || true
wp option update woocommerce_task_list_hidden "yes" >/dev/null 2>&1 || true

log "Shipping zone and payment gateways (cash on delivery + bank transfer)"
wp eval '
  $zones = WC_Shipping_Zones::get_zones();
  if (!$zones) {
    $zone = new WC_Shipping_Zone(); $zone->set_zone_name("Everywhere"); $zone->save();
    $zone->add_shipping_method("flat_rate"); $zone->save();
    $zone->add_shipping_method("free_shipping"); $zone->save();
    echo "Shipping zone created\n";
  }
  update_option("woocommerce_cod_settings", array_merge((array) get_option("woocommerce_cod_settings", []), ["enabled" => "yes"]));
  update_option("woocommerce_bacs_settings", array_merge((array) get_option("woocommerce_bacs_settings", []), ["enabled" => "yes"]));
'

log "Activating the Flipick plugin"
wp plugin is-active flipick-video-generator || wp plugin activate flipick-video-generator

log "Seeding demo data"
wp eval-file /seed/seed.php

log "REST API keys (read/write)"
if [ -f .env.local ] && grep -q '^WC_CONSUMER_KEY=ck_' .env.local; then
  echo "Keys already present in .env.local"
else
  KEYS=$(wp eval '
    global $wpdb;
    $ck = "ck_" . wc_rand_hash(); $cs = "cs_" . wc_rand_hash();
    $wpdb->insert($wpdb->prefix . "woocommerce_api_keys", [
      "user_id" => 1, "description" => "Flipick adapter (local)", "permissions" => "read_write",
      "consumer_key" => wc_api_hash($ck), "consumer_secret" => $cs, "truncated_key" => substr($ck, -7),
    ]);
    echo $ck . ":" . $cs;
  ' | tail -n 1 | tr -d '\r')
  case "$KEYS" in ck_*:cs_*) ;; *) echo "Could not create API keys (got: $KEYS)" >&2; exit 1 ;; esac
  {
    echo "# Generated by setup.sh -- git-ignored. Local development keys only."
    echo "WC_SITE_URL=${WP_SITE_URL}"
    echo "WC_CONSUMER_KEY=${KEYS%%:*}"
    echo "WC_CONSUMER_SECRET=${KEYS##*:}"
  } > .env.local
  echo "Wrote .env.local"
fi

log "Webhooks (product + order events) pointing at the adapter"
# The plugin registers its own signed webhooks when the store is connected to the adapter (the secret is the install secret).
# For adapter-less experiments a plain "ping" webhook is created here so the delivery log in WooCommerce has traffic.
wp eval '
  $ds = WC_Data_Store::load("webhook");
  $names = ["Flipick local: product updated", "Flipick local: order created", "Flipick local: order updated"];
  $existing = array_map(function ($id) { return wc_get_webhook($id)->get_name(); }, $ds->get_webhooks_ids());
  $topics = ["product.updated", "order.created", "order.updated"];
  foreach ($names as $i => $name) {
    if (in_array($name, $existing, true)) { continue; }
    $w = new WC_Webhook();
    $w->set_name($name); $w->set_user_id(1); $w->set_topic($topics[$i]);
    $w->set_secret("local-dev-webhook-secret");
    $w->set_delivery_url(getenv("FLIPICK_ADAPTER_URL") ? rtrim(getenv("FLIPICK_ADAPTER_URL"), "/") . "/api/webhooks/woocommerce/local-dev" : "http://host.docker.internal:4300/api/webhooks/woocommerce/local-dev");
    $w->set_status("paused");
    $w->save();
    echo "Created webhook $name (paused until the store is connected)\n";
  }
'

log "Done"
echo "Store:   ${WP_SITE_URL}   admin: ${WP_ADMIN_USER} / (see .env)"
echo "API:     ${WP_SITE_URL}/wp-json/wc/v3/products  (keys in .env.local)"
echo "Verify:  node verify.js"
